In [1]:
##Question 1: Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr=arr[::-1]
    return numpy.array(arr,dtype=float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
##Question 2: Shape and Reshape
import numpy
list=input().split(" ")
array=numpy.array(list,dtype=int)
array=numpy.reshape(array,(3,3))
print(array)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
##Question 3: Transpose and Flatten
import numpy
l=[]
a,b=map(int,input().split(" "))
for _ in range(a):
    i=input().split(" ")
    l.extend(i)
z=numpy.array(l,dtype=int)
print(numpy.transpose(numpy.reshape(z,(a,b))))
print(z)

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
## Question 4: Concatenate 
import numpy
a,b,c=map(int,input().split(" "))
l=[]
for _ in range(a):
    z=map(int,input().split(" "))
    l.extend(z)
arr=numpy.reshape(numpy.array(l),(a,c))
l=[]
for _ in range(b):
    z=map(int,input().split(" "))
    l.extend(z)
arr1=numpy.reshape(numpy.array(l),(b,c))
print(numpy.concatenate((arr,arr1),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [5]:
##Question 5: Zeros and Ones
import numpy
a=[int(i) for i in input().split(" ")]
a=tuple(a)
print(numpy.zeros(a,dtype=int))
print(numpy.ones(a,dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
##Question 6: Eye and Identity
import numpy
numpy.set_printoptions(legacy='1.13')
n,m=map(int,input().split(" "))
print(numpy.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
##Question 7: Array Mathematics
import numpy
a,b=map(int,input().split(" "))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,b))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr1=numpy.array(l)
arr1=numpy.reshape(arr1,(a,b))
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)
print(arr//arr1)
print(arr%arr1)
print(arr**arr1) 

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [9]:
##Question 8: Floor,Ceil and Rint
import numpy
numpy.set_printoptions(legacy="1.13")
l=input().split(" ")
arr=numpy.array(l,dtype=float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [10]:
##Question 9: sum and prod
import numpy
a,b=map(int,input().split(" "))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,b))
print(numpy.prod(numpy.sum(arr,axis=0)))

2 2
1 2
3 4
24


In [11]:
##Question 10:Min and Max
import numpy
a,b=map(int,input().split(" "))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,b))
print(numpy.max(numpy.min(arr,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [12]:
##Question 11: Mean,Var and Std
import numpy
a,b=map(int,input().split(" "))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,b))
print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(numpy.rint(numpy.std(arr)*10**11)/10**11)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [13]:
##Question 12: Dot and Cross
import numpy
a=int(input())
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,a))
l=[]
for _ in range(a):
    z=[int(i) for i in input().split(" ")]
    l.extend(z)
arr1=numpy.array(l)
arr1=numpy.reshape(arr1,(a,a))
print(numpy.dot(arr,arr1))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
##Question 13: Inner and Outer
import numpy
arr = numpy.array(input().split(), dtype=int)
arr1 = numpy.array(input().split(), dtype=int)
print(numpy.inner(arr,arr1))
print(numpy.outer(arr,arr1))

In [18]:
##Question 14: Polynomials
import numpy
a=[float(i) for i in input().split(" ")]
b=float(input())
c=len(a)-1
ans=0.0
for i in a:
    ans+=i*(b**c)
    c-=1
print(ans)

1.1 2 3
0
3.0


In [17]:
##Question 15: Linear Algebra
import numpy
a=int(input())
l=[]
for _ in range(a):
    z=[float(i) for i in input().split(" ")]
    l.extend(z)
arr=numpy.array(l)
arr=numpy.reshape(arr,(a,a))
print(numpy.rint(numpy.linalg.det(arr)*100)/100)

2
1.1 1.1
1.1 1.2
0.11
